# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qchainage_dialog_widget.ui'
#
# Created: Wed Oct 17 09:04:03 2012
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(380, 367)
        Dialog.setMinimumSize(QtCore.QSize(380, 200))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelSelectLayer = QtGui.QLabel(Dialog)
        self.labelSelectLayer.setObjectName(_fromUtf8("labelSelectLayer"))
        self.gridLayout.addWidget(self.labelSelectLayer, 0, 0, 1, 1)
        self.selectLayerComboBox = QtGui.QComboBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectLayerComboBox.sizePolicy().hasHeightForWidth())
        self.selectLayerComboBox.setSizePolicy(sizePolicy)
        self.selectLayerComboBox.setObjectName(_fromUtf8("selectLayerComboBox"))
        self.gridLayout.addWidget(self.selectLayerComboBox, 0, 1, 1, 1)
        self.labelLayerName = QtGui.QLabel(Dialog)
        self.labelLayerName.setObjectName(_fromUtf8("labelLayerName"))
        self.gridLayout.addWidget(self.labelLayerName, 1, 0, 1, 1)
        self.layerNameLine = QtGui.QLineEdit(Dialog)
        self.layerNameLine.setObjectName(_fromUtf8("layerNameLine"))
        self.gridLayout.addWidget(self.layerNameLine, 1, 1, 1, 1)
        self.labelDistance = QtGui.QLabel(Dialog)
        self.labelDistance.setObjectName(_fromUtf8("labelDistance"))
        self.gridLayout.addWidget(self.labelDistance, 2, 0, 1, 1)
        self.distanceSpinBox = QtGui.QDoubleSpinBox(Dialog)
        self.distanceSpinBox.setDecimals(3)
        self.distanceSpinBox.setMaximum(9999.99)
        self.distanceSpinBox.setProperty("value", 1.0)
        self.distanceSpinBox.setObjectName(_fromUtf8("distanceSpinBox"))
        self.gridLayout.addWidget(self.distanceSpinBox, 2, 1, 1, 1)
        self.checkBoxStartEnd = QtGui.QCheckBox(Dialog)
        self.checkBoxStartEnd.setObjectName(_fromUtf8("checkBoxStartEnd"))
        self.gridLayout.addWidget(self.checkBoxStartEnd, 3, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelStart = QtGui.QLabel(Dialog)
        self.labelStart.setEnabled(False)
        self.labelStart.setObjectName(_fromUtf8("labelStart"))
        self.horizontalLayout.addWidget(self.labelStart)
        self.startpointSpinBox = QtGui.QDoubleSpinBox(Dialog)
        self.startpointSpinBox.setEnabled(False)
        self.startpointSpinBox.setDecimals(3)
        self.startpointSpinBox.setMaximum(9999.99)
        self.startpointSpinBox.setObjectName(_fromUtf8("startpointSpinBox"))
        self.horizontalLayout.addWidget(self.startpointSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelEnd = QtGui.QLabel(Dialog)
        self.labelEnd.setEnabled(False)
        self.labelEnd.setObjectName(_fromUtf8("labelEnd"))
        self.horizontalLayout_2.addWidget(self.labelEnd)
        self.endpointSpinBox = QtGui.QDoubleSpinBox(Dialog)
        self.endpointSpinBox.setEnabled(False)
        self.endpointSpinBox.setDecimals(3)
        self.endpointSpinBox.setMaximum(9999.99)
        self.endpointSpinBox.setObjectName(_fromUtf8("endpointSpinBox"))
        self.horizontalLayout_2.addWidget(self.endpointSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 3, 1, 2, 1)
        self.checkBoxStartEnd_2 = QtGui.QCheckBox(Dialog)
        self.checkBoxStartEnd_2.setObjectName(_fromUtf8("checkBoxStartEnd_2"))
        self.gridLayout.addWidget(self.checkBoxStartEnd_2, 4, 0, 1, 1)
        self.chainageGroupBox = QtGui.QGroupBox(Dialog)
        self.chainageGroupBox.setObjectName(_fromUtf8("chainageGroupBox"))
        self.selectAllRadioButton = QtGui.QRadioButton(self.chainageGroupBox)
        self.selectAllRadioButton.setEnabled(True)
        self.selectAllRadioButton.setGeometry(QtCore.QRect(17, 57, 173, 26))
        self.selectAllRadioButton.setCheckable(True)
        self.selectAllRadioButton.setObjectName(_fromUtf8("selectAllRadioButton"))
        self.selectOnlyRadioButton = QtGui.QRadioButton(self.chainageGroupBox)
        self.selectOnlyRadioButton.setEnabled(True)
        self.selectOnlyRadioButton.setGeometry(QtCore.QRect(17, 25, 178, 26))
        self.selectOnlyRadioButton.setCheckable(True)
        self.selectOnlyRadioButton.setChecked(False)
        self.selectOnlyRadioButton.setObjectName(_fromUtf8("selectOnlyRadioButton"))
        self.gridLayout.addWidget(self.chainageGroupBox, 5, 0, 1, 2)
        self.autoLabelCheckBox = QtGui.QCheckBox(Dialog)
        self.autoLabelCheckBox.setEnabled(False)
        self.autoLabelCheckBox.setChecked(True)
        self.autoLabelCheckBox.setObjectName(_fromUtf8("autoLabelCheckBox"))
        self.gridLayout.addWidget(self.autoLabelCheckBox, 6, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 7, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.selectLayerComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.onComboBoxChanged)
        QtCore.QObject.connect(self.checkBoxStartEnd, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.startpointSpinBox.setEnabled)
        QtCore.QObject.connect(self.checkBoxStartEnd, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelStart.setEnabled)
        QtCore.QObject.connect(self.checkBoxStartEnd_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.endpointSpinBox.setEnabled)
        QtCore.QObject.connect(self.checkBoxStartEnd_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelEnd.setEnabled)
        QtCore.QObject.connect(self.selectLayerComboBox, QtCore.SIGNAL(_fromUtf8("highlighted(int)")), Dialog.onComboBoxTouched)
        QtCore.QObject.connect(self.selectAllRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), Dialog.onRadioAll)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelectLayer.setText(QtGui.QApplication.translate("Dialog", "Select Layer to chainage", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLayerName.setText(QtGui.QApplication.translate("Dialog", "Name of output Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDistance.setText(QtGui.QApplication.translate("Dialog", "Distance to chainage", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxStartEnd.setText(QtGui.QApplication.translate("Dialog", "Activate Startpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStart.setText(QtGui.QApplication.translate("Dialog", "Start from ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelEnd.setText(QtGui.QApplication.translate("Dialog", "End at", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxStartEnd_2.setText(QtGui.QApplication.translate("Dialog", "Activate Endpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.chainageGroupBox.setTitle(QtGui.QApplication.translate("Dialog", "Chainage", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAllRadioButton.setText(QtGui.QApplication.translate("Dialog", "all Features in Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.selectOnlyRadioButton.setText(QtGui.QApplication.translate("Dialog", "only selected Features", None, QtGui.QApplication.UnicodeUTF8))
        self.autoLabelCheckBox.setText(QtGui.QApplication.translate("Dialog", "Automatically Label the Layer", None, QtGui.QApplication.UnicodeUTF8))

