# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qchainage.ui'
#
# Created: Fri Sep 13 21:46:08 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QChainageDialog(object):
    def setupUi(self, QChainageDialog):
        QChainageDialog.setObjectName(_fromUtf8("QChainageDialog"))
        QChainageDialog.setEnabled(True)
        QChainageDialog.resize(442, 248)
        QChainageDialog.setMinimumSize(QtCore.QSize(380, 200))
        self.gridLayout = QtGui.QGridLayout(QChainageDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(QChainageDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 345))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelSelectLayer = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.labelSelectLayer.setObjectName(_fromUtf8("labelSelectLayer"))
        self.horizontalLayout_5.addWidget(self.labelSelectLayer)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.selectLayerComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectLayerComboBox.sizePolicy().hasHeightForWidth())
        self.selectLayerComboBox.setSizePolicy(sizePolicy)
        self.selectLayerComboBox.setObjectName(_fromUtf8("selectLayerComboBox"))
        self.horizontalLayout_5.addWidget(self.selectLayerComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelLayerName = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.labelLayerName.setObjectName(_fromUtf8("labelLayerName"))
        self.horizontalLayout_4.addWidget(self.labelLayerName)
        self.layerNameLine = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.layerNameLine.setObjectName(_fromUtf8("layerNameLine"))
        self.horizontalLayout_4.addWidget(self.layerNameLine)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelDistance = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.labelDistance.setObjectName(_fromUtf8("labelDistance"))
        self.horizontalLayout_2.addWidget(self.labelDistance)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.distanceSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.distanceSpinBox.setDecimals(6)
        self.distanceSpinBox.setMaximum(9999.999999)
        self.distanceSpinBox.setProperty("value", 1.0)
        self.distanceSpinBox.setObjectName(_fromUtf8("distanceSpinBox"))
        self.horizontalLayout_3.addWidget(self.distanceSpinBox)
        self.labelUnit = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.labelUnit.setObjectName(_fromUtf8("labelUnit"))
        self.horizontalLayout_3.addWidget(self.labelUnit)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.autoLabelCheckBox = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.autoLabelCheckBox.setEnabled(True)
        self.autoLabelCheckBox.setChecked(True)
        self.autoLabelCheckBox.setObjectName(_fromUtf8("autoLabelCheckBox"))
        self.verticalLayout.addWidget(self.autoLabelCheckBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.chainageGroupBox = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.chainageGroupBox.setObjectName(_fromUtf8("chainageGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.chainageGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.selectOnlyRadioButton = QtGui.QRadioButton(self.chainageGroupBox)
        self.selectOnlyRadioButton.setEnabled(True)
        self.selectOnlyRadioButton.setCheckable(True)
        self.selectOnlyRadioButton.setChecked(False)
        self.selectOnlyRadioButton.setObjectName(_fromUtf8("selectOnlyRadioButton"))
        self.verticalLayout_3.addWidget(self.selectOnlyRadioButton)
        self.selectAllRadioButton = QtGui.QRadioButton(self.chainageGroupBox)
        self.selectAllRadioButton.setEnabled(True)
        self.selectAllRadioButton.setCheckable(True)
        self.selectAllRadioButton.setObjectName(_fromUtf8("selectAllRadioButton"))
        self.verticalLayout_3.addWidget(self.selectAllRadioButton)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.checkBoxStartEnd = QtGui.QCheckBox(self.chainageGroupBox)
        self.checkBoxStartEnd.setObjectName(_fromUtf8("checkBoxStartEnd"))
        self.verticalLayout_6.addWidget(self.checkBoxStartEnd)
        self.checkBoxStartEnd_2 = QtGui.QCheckBox(self.chainageGroupBox)
        self.checkBoxStartEnd_2.setObjectName(_fromUtf8("checkBoxStartEnd_2"))
        self.verticalLayout_6.addWidget(self.checkBoxStartEnd_2)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelStart = QtGui.QLabel(self.chainageGroupBox)
        self.labelStart.setEnabled(False)
        self.labelStart.setObjectName(_fromUtf8("labelStart"))
        self.verticalLayout_4.addWidget(self.labelStart)
        self.labelEnd = QtGui.QLabel(self.chainageGroupBox)
        self.labelEnd.setEnabled(False)
        self.labelEnd.setObjectName(_fromUtf8("labelEnd"))
        self.verticalLayout_4.addWidget(self.labelEnd)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.startpointSpinBox = QtGui.QDoubleSpinBox(self.chainageGroupBox)
        self.startpointSpinBox.setEnabled(False)
        self.startpointSpinBox.setDecimals(3)
        self.startpointSpinBox.setMaximum(9999.99)
        self.startpointSpinBox.setObjectName(_fromUtf8("startpointSpinBox"))
        self.verticalLayout_2.addWidget(self.startpointSpinBox)
        self.endpointSpinBox = QtGui.QDoubleSpinBox(self.chainageGroupBox)
        self.endpointSpinBox.setEnabled(False)
        self.endpointSpinBox.setDecimals(3)
        self.endpointSpinBox.setMaximum(9999.99)
        self.endpointSpinBox.setObjectName(_fromUtf8("endpointSpinBox"))
        self.verticalLayout_2.addWidget(self.endpointSpinBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.chainageGroupBox, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(QChainageDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(QChainageDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), QChainageDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), QChainageDialog.reject)
        QtCore.QObject.connect(self.checkBoxStartEnd_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.endpointSpinBox.setEnabled)
        QtCore.QObject.connect(self.checkBoxStartEnd_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelEnd.setEnabled)
        QtCore.QObject.connect(self.checkBoxStartEnd, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.startpointSpinBox.setEnabled)
        QtCore.QObject.connect(self.checkBoxStartEnd, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelStart.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(QChainageDialog)

    def retranslateUi(self, QChainageDialog):
        QChainageDialog.setWindowTitle(_translate("QChainageDialog", "Dialog", None))
        self.labelSelectLayer.setText(_translate("QChainageDialog", "Select Layer to chainage", None))
        self.labelLayerName.setText(_translate("QChainageDialog", "Name of output Layer", None))
        self.labelDistance.setText(_translate("QChainageDialog", "Chainage every", None))
        self.labelUnit.setText(_translate("QChainageDialog", "Units", None))
        self.autoLabelCheckBox.setText(_translate("QChainageDialog", "Automatically Label the Layer", None))
        self.chainageGroupBox.setTitle(_translate("QChainageDialog", "Advanced Features", None))
        self.selectOnlyRadioButton.setText(_translate("QChainageDialog", "only selected Features", None))
        self.selectAllRadioButton.setText(_translate("QChainageDialog", "all Features in Layer", None))
        self.checkBoxStartEnd.setText(_translate("QChainageDialog", "Activate Startpoint", None))
        self.checkBoxStartEnd_2.setText(_translate("QChainageDialog", "Activate Endpoint", None))
        self.labelStart.setText(_translate("QChainageDialog", "Start from ", None))
        self.labelEnd.setText(_translate("QChainageDialog", "End at", None))

from qgis.gui import QgsCollapsibleGroupBox
